package llm

import "strings"

// CorrectOutput applies deterministic corrections to text generated by an LLM.
// Keep this list small and explicit: these replacements are a final output
// safeguard for recurring typos, not a substitute for model instructions.
func CorrectOutput(text string) string {
	return strings.ReplaceAll(text, "뉤앙스가", "뉘앙스가")
}
